"""fix column widths and revert session_record extras

Revision ID: b6511fbcadc5
Revises: e0c57e65aefc
Create Date: 2026-05-12 13:25:48.497878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6511fbcadc5'
down_revision: Union[str, None] = 'e0c57e65aefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('cases', 'phone_home',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('cases', 'emergency_contact',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('cases', 'emergency_phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('cases', 'emergency_phone2',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('session_records', 'room_name')
    op.drop_column('session_records', 'commission_rate')
    op.drop_column('session_records', 'payment_method')
    op.drop_column('session_records', 'clinic_share')
    op.drop_column('session_records', 'case_name')
    op.drop_column('session_records', 'therapist_paid')
    op.drop_column('session_records', 'funding_source')
    op.drop_column('session_records', 'hours')
    op.drop_column('session_records', 'notes')
    op.drop_column('session_records', 'session_category')
    op.drop_column('session_records', 'session_format')
    op.drop_column('session_records', 'therapist_share')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_records', sa.Column('therapist_share', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('session_records', sa.Column('session_format', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('session_records', sa.Column('session_category', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('session_records', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('session_records', sa.Column('hours', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True))
    op.add_column('session_records', sa.Column('funding_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('session_records', sa.Column('therapist_paid', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('session_records', sa.Column('case_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('session_records', sa.Column('clinic_share', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('session_records', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('session_records', sa.Column('commission_rate', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.add_column('session_records', sa.Column('room_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('cases', 'emergency_phone2',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('cases', 'emergency_phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('cases', 'emergency_contact',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('cases', 'phone_home',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('cases', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
