"""expand case and session_record for excel import

Revision ID: e0c57e65aefc
Revises: 2348f74352ff
Create Date: 2026-05-12 13:20:48.520694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c57e65aefc'
down_revision: Union[str, None] = '2348f74352ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_code', sa.String(length=20), nullable=True))
    op.add_column('cases', sa.Column('phone_home', sa.String(length=30), nullable=True))
    op.add_column('cases', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('cases', sa.Column('emergency_phone', sa.String(length=30), nullable=True))
    op.add_column('cases', sa.Column('emergency_phone2', sa.String(length=30), nullable=True))
    op.add_column('cases', sa.Column('referral_source', sa.String(length=200), nullable=True))
    op.add_column('cases', sa.Column('session_location', sa.String(length=200), nullable=True))
    op.alter_column('cases', 'funding_source',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_cases_case_code'), 'cases', ['case_code'], unique=False)
    op.add_column('session_records', sa.Column('case_name', sa.String(length=100), nullable=True))
    op.add_column('session_records', sa.Column('room_name', sa.String(length=50), nullable=True))
    op.add_column('session_records', sa.Column('funding_source', sa.String(length=100), nullable=True))
    op.add_column('session_records', sa.Column('commission_rate', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('session_records', sa.Column('therapist_share', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('session_records', sa.Column('clinic_share', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('session_records', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('session_records', sa.Column('session_format', sa.String(length=20), nullable=True))
    op.add_column('session_records', sa.Column('session_category', sa.String(length=20), nullable=True))
    op.add_column('session_records', sa.Column('hours', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('session_records', sa.Column('therapist_paid', sa.String(length=20), nullable=True))
    op.add_column('session_records', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('session_records', 'appointment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('session_records', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_records', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session_records', 'appointment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('session_records', 'notes')
    op.drop_column('session_records', 'therapist_paid')
    op.drop_column('session_records', 'hours')
    op.drop_column('session_records', 'session_category')
    op.drop_column('session_records', 'session_format')
    op.drop_column('session_records', 'payment_method')
    op.drop_column('session_records', 'clinic_share')
    op.drop_column('session_records', 'therapist_share')
    op.drop_column('session_records', 'commission_rate')
    op.drop_column('session_records', 'funding_source')
    op.drop_column('session_records', 'room_name')
    op.drop_column('session_records', 'case_name')
    op.drop_index(op.f('ix_cases_case_code'), table_name='cases')
    op.alter_column('cases', 'funding_source',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('cases', 'session_location')
    op.drop_column('cases', 'referral_source')
    op.drop_column('cases', 'emergency_phone2')
    op.drop_column('cases', 'emergency_phone')
    op.drop_column('cases', 'address')
    op.drop_column('cases', 'phone_home')
    op.drop_column('cases', 'case_code')
    # ### end Alembic commands ###
