"""add institutions table and refactor case funding

Revision ID: e4afc95f938e
Revises: b6511fbcadc5
Create Date: 2026-05-12 13:48:28.750490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4afc95f938e'
down_revision: Union[str, None] = 'b6511fbcadc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('cases', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.alter_column('cases', 'funding_source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'cases', 'institutions', ['institution_id'], ['id'])
    op.drop_column('cases', 'institution_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('institution_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.alter_column('cases', 'funding_source',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('cases', 'institution_id')
    op.drop_table('institutions')
    # ### end Alembic commands ###
